apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blockchain-api
  template:
    metadata:
      labels:
        app: blockchain-api
    spec:
      containers:
      - name: blockchain-api
        image: swpnit/blockchain-api:latest
        ports:
        - containerPort: 8080