---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: geth-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/geth
    server: 172.16.35.9
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: geth-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
