apiVersion: v1
kind: Service
metadata:
  name: blockchain-api-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: blockchain-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080