---
apiVersion: v1
kind: Service
metadata:
  name: remix
  labels:
    app: remix
spec:
  type: NodePort
  selector:
    app: remix
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix
  labels:
    app: remix
spec:
  selector:
    matchLabels:
      app: remix
  replicas: 1
  template:
    metadata:
      name: remix
      labels:
        app: remix
    spec:
      containers:
      - name: remix
        image: remixproject/remix-ide
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.5"
