apiVersion: v1
kind: Service
metadata:
  name: remix-ide-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: solidity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80