name: Mint more NFTs
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Number of NFTs to mint'
        required: true
        default: '10'
jobs:
  mint:
    name: Mint NFTs
    runs-on: ubuntu-latest
    steps: 
      - name: Clone Repository
        uses: actions/checkout@v2
      
      - name: ❄️ Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn

      - name: Install CLI
        uses: dopplerhq/cli-action@v1

      - name: Use the correct Truffle file
        run: |
          rm truffle-config.js
          mv truffle-config-ci.js truffle-config.js

      - name: Truffle Mint
        run: doppler run --command "node_modules/.bin/truffle exec devops/mint.js --network rinkeby --nfts ${{ github.event.inputs.name }}" --token=${{secrets.DOPPLER_TOKEN}}

      - name: Checkout Lambda repo
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_TOKEN}}
          repository: silviopaganini/nft-market-service
          path: lambda
          ref: master

      - name: Update DB
        run: |
          cd lambda
          rm db/index.ts
          mv ../db.ts db/index.ts

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .
          git commit -m "update database"
          git push origin master

      