[package]
name = "nft"
version = "0.1.0"
authors = ["Daniel Graczer <daniel@fleek.co>"]
edition = "2018"

[dependencies]
ic-kit = "0.4.3"
ic-cdk = "0.4.0"
common = {path = "../common"}
serde = { version="1.0.136", features = ["derive"] }
derive-new = "0.5"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
